apiVersion: v1
kind: Secret
metadata:
  name: fintrack-secret
  namespace: default
type: Opaque
# Values are base64-encoded. To encode: echo -n 'your-value' | base64
data:
  # "fintrack-super-secret-key" base64 encoded
  SECRET_KEY: ZmludHJhY2stc3VwZXItc2VjcmV0LWtleQ==
